# /etc/fluent-bit/conf.d/51-freeipa-filters.conf
# FreeIPA: нормализация полей + Lua-обогащение + метаданные.
# Управляется Ansible (роль fb_freeipa). Не редактировать вручную.

[FILTER]
    Name        modify
    Match       freeipa.httpd.access
    Rename      source_ip source.ip
    Rename      user_name user.name
    Rename      http_request_method http.request.method
    Rename      url_path url.path
    Rename      http_response_status_code http.response.status_code
    Rename      http_response_body_bytes http.response.body.bytes

[FILTER]
    Name        modify
    Match       freeipa.dirsrv.access
    Rename      ldap_connection_id ldap.connection.id
    Rename      ldap_operation_id ldap.operation.id

[FILTER]
    Name        modify
    Match       freeipa.dns
    Rename      dns_category dns.category

[FILTER]
    Name        modify
    Match       freeipa.dirsrv.audit*
    Rename      ldap_dn ldap.dn

[FILTER]
    Name             modify
    Match            freeipa.kdc
    Add              service.name kerberos

[FILTER]
    Name             modify
    Match            freeipa.httpd.*
    Add              service.name httpd

[FILTER]
    Name             modify
    Match            freeipa.dirsrv.*
    Add              service.name ldap

[FILTER]
    Name             modify
    Match            freeipa.dns
    Add              service.name dns

[FILTER]
    Name             modify
    Match            freeipa.dogtag
    Add              service.name dogtag

[FILTER]
    Name             modify
    Match            freeipa.sssd
    Add              service.name sssd

[FILTER]
    Name             lua
    Match            freeipa.*
    script           /etc/fluent-bit/scripts/freeipa.lua
    call             normalize

[FILTER]
    Name    record_modifier
    Match   freeipa.*
    Record  source_type freeipa
