[logstash]
# Укажите hostname или IP целевого хоста:
# logstash-prod  ansible_host=10.0.0.5

[logstash:vars]
ansible_user=installer
ansible_python_interpreter=/usr/bin/python3
# Если installer в группе docker — become не нужен.
# ansible_become=true
# ansible_become_method=sudo
