input {
  tcp { port => 5044 }
  udp { port => 5514 }
}

filter {
  if [message] =~ /^\{.*/ {
    json { source => "message" }
  }

  if [source_type] {
    mutate {
      add_field => { "[@metadata][target_index]" => "data_%{source_type}" }
    }
  } else {
    mutate {
      add_field => { "[@metadata][target_index]" => "logs-general-%{+YYYY_MM_dd}" }
    }
  }
  
  mutate {
    lowercase => ["[@metadata][target_index]"]
  }
}

output {
  opensearch {
    hosts => ["https://opensearch:9200"]
    auth_type => "basic"
    user => "admin"
    password => "${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"
    ssl => true
    ssl_certificate_verification => false
    index => "%{[@metadata][target_index]}"
    action => "create"
  }
}
