# /etc/fluent-bit/conf.d/88-client-metadata.conf
# Метаданные для всех клиентских тегов: fqdn + source_type=docker_container.
# Управляется Ansible (роль fluent_bit). Не редактировать вручную.

[FILTER]
    Name        record_modifier
    Match_Regex ^(docker\.|freeipa\.|docker_events$|suricata_json$|waf_json$|osquery_json$)
    Record      fqdn ${HOSTNAME}

[FILTER]
    Name    record_modifier
    Match   docker.*
    Record  source_type docker_container

[FILTER]
    Name    modify
    Match   docker.*
    Rename  log unparsed_log
