---
# FreeIPA-хост: полный базовый стек
# KDC + httpd + 389DS + Dogtag CA + BIND DNS + SSSD + docker + osquery_client + suricata + waf
base_stack:
  - freeipa
  - docker_events
#  - suricata
#  - waf
