[logstash]
10.202.77.81

[logstash:vars]
ansible_user=installer
ansible_python_interpreter=/usr/bin/python3
# Если installer в группе docker — become не нужен.
# Если нет прав на /opt — раскомментировать:
# ansible_become=true
# ansible_become_method=sudo
